// Public TypeScript API for @databricks/zerobus-ingest-sdk.
//
// The native bindings under `../index.js` (generated by napi-rs from `lib.rs`)
// are the implementation detail. This module is the stable, published surface.
//
// API style: **options-bag** matching Python's kwargs idiom. Every entry point
// takes a plain object whose fields are either primitive options or
// discriminated-union variants (`auth`, `format`). To extend the API:
//
// - Add a new optional field to an options interface — non-breaking.
// - Add a new arm to a discriminated union — non-breaking for existing callers.
// - Reshape an existing field — major version bump.
//
// This is more evolvable than a fluent builder because adding methods to a
// class is a public-surface change, while adding optional object fields is
// invisible to callers who don't use them.

import * as native from '../index.js';

export { ZerobusError } from '../index.js';

// ---------------------------------------------------------------------------
// Enums (plain const objects so they survive --isolatedModules)
// ---------------------------------------------------------------------------

export const ArrowDataType = {
    Boolean: 0,
    Int8: 1,
    Int16: 2,
    Int32: 3,
    Int64: 4,
    UInt8: 5,
    UInt16: 6,
    UInt32: 7,
    UInt64: 8,
    Float32: 9,
    Float64: 10,
    Utf8: 11,
    LargeUtf8: 12,
    Binary: 13,
    LargeBinary: 14,
    Date32: 15,
    Date64: 16,
    TimestampMicros: 17,
    TimestampNanos: 18,
} as const;
export type ArrowDataType = (typeof ArrowDataType)[keyof typeof ArrowDataType];

/** Arrow IPC payload compression. `'none'` keeps the SDK on the zero-copy forward path. */
export type Compression = 'none' | 'lz4_frame' | 'zstd';

function compressionToNative(c: Compression | undefined): number | undefined {
    if (c === undefined || c === 'none') return undefined;
    if (c === 'lz4_frame') return 0;
    if (c === 'zstd') return 1;
    throw new Error(`Unknown compression mode: ${c}`);
}

// ---------------------------------------------------------------------------
// SDK config
// ---------------------------------------------------------------------------

export interface SdkOptions {
    /** Zerobus endpoint URL. May be schemeless; `https://` is prepended unless `tls === 'none'`. */
    endpoint: string;
    /** Unity Catalog endpoint URL. Required for OAuth; optional when using a custom headers provider. */
    unityCatalogUrl?: string;
    /**
     * TLS strategy. Defaults to `'secure'` (system CA certificates).
     * `'none'` lets you connect to plaintext `http://` endpoints (local dev or
     * sidecar proxies that terminate TLS).
     */
    tls?: 'secure' | 'none';
    /**
     * Optional application identifier appended to the `user-agent` HTTP
     * header. Convention: `'<product>/<version>'`. The default SDK prefix
     * (`zerobus-sdk-ts/<version>`) is preserved unless `sdkIdentifier` is set.
     */
    applicationName?: string;
    /**
     * Override the SDK prefix of the `user-agent` header. Defaults to
     * `zerobus-sdk-ts/<version>`. Rarely needed; intended for embedders that
     * re-wrap this SDK.
     */
    sdkIdentifier?: string;
}

// ---------------------------------------------------------------------------
// Auth + format discriminated unions
// ---------------------------------------------------------------------------

export type Auth =
    | { type: 'oauth'; clientId: string; clientSecret: string }
    | {
          type: 'headersProvider';
          /** Called once per stream creation. Must include `authorization` and `x-databricks-zerobus-table-name`. */
          getHeaders: () => Promise<Array<[string, string]>>;
      }
    | {
          /**
           * No real auth. The SDK still requires the canonical headers, so the
           * facade synthesizes them with a placeholder bearer token. Intended
           * for local-only servers / sidecar-proxy deployments.
           */
          type: 'noAuth';
      };

export type GrpcFormat =
    | { type: 'json' }
    | {
          type: 'proto';
          /** Base64-encoded `DescriptorProto` for the message type. */
          descriptor: string;
      };

// ---------------------------------------------------------------------------
// Stream options
// ---------------------------------------------------------------------------

interface CommonStreamOptions {
    /** Fully-qualified Unity Catalog table name, `catalog.schema.table`. */
    table: string;
    auth: Auth;
    recovery?: boolean;
    recoveryTimeoutMs?: number;
    recoveryBackoffMs?: number;
    recoveryRetries?: number;
    serverLackOfAckTimeoutMs?: number;
    flushTimeoutMs?: number;
    streamPausedMaxWaitTimeMs?: number;
}

export interface CreateStreamOptions extends CommonStreamOptions {
    format: GrpcFormat;
    maxInflightRequests?: number;
}

export interface ArrowField {
    name: string;
    dataType: ArrowDataType;
    /** Defaults to `true`. */
    nullable?: boolean;
}

export interface CreateArrowStreamOptions extends CommonStreamOptions {
    /** Arrow schema. The stream rejects RecordBatches whose schema differs. */
    schema: ArrowField[];
    /** Default `'none'` (zero-copy IPC forwarding). */
    compression?: Compression;
    maxInflightBatches?: number;
    connectionTimeoutMs?: number;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Build a headers callback that returns the required `authorization` +
 * `x-databricks-zerobus-table-name` headers. Useful for PAT-style auth or
 * sidecar-proxy deployments where you control the token lifetime yourself.
 */
export function bearerTokenProvider(
    table: string,
    getToken: () => string | Promise<string>,
): () => Promise<Array<[string, string]>> {
    return async () => {
        const token = await getToken();
        return [
            ['authorization', `Bearer ${token}`],
            ['x-databricks-zerobus-table-name', table],
        ];
    };
}

function authToNative(
    auth: Auth,
    table: string,
): { clientId: string; clientSecret: string; headersProvider?: native.JsHeadersProvider } {
    if (auth.type === 'oauth') {
        return { clientId: auth.clientId, clientSecret: auth.clientSecret };
    }
    if (auth.type === 'headersProvider') {
        const cb = auth.getHeaders;
        return {
            clientId: '',
            clientSecret: '',
            headersProvider: { getHeadersCallback: cb as unknown as native.JsHeadersProvider['getHeadersCallback'] },
        };
    }
    // noAuth: synthesize a callback returning placeholders the Rust SDK accepts.
    const placeholder = bearerTokenProvider(table, () => 'noauth');
    return {
        clientId: '',
        clientSecret: '',
        headersProvider: {
            getHeadersCallback: placeholder as unknown as native.JsHeadersProvider['getHeadersCallback'],
        },
    };
}

function toNativeStreamOptions(o: CreateStreamOptions): native.StreamConfigurationOptions {
    const recordType = o.format.type === 'json' ? 0 : 1;
    return {
        recordType,
        recovery: o.recovery,
        recoveryTimeoutMs: o.recoveryTimeoutMs,
        recoveryBackoffMs: o.recoveryBackoffMs,
        recoveryRetries: o.recoveryRetries,
        serverLackOfAckTimeoutMs: o.serverLackOfAckTimeoutMs,
        flushTimeoutMs: o.flushTimeoutMs,
        maxInflightRequests: o.maxInflightRequests,
        streamPausedMaxWaitTimeMs: o.streamPausedMaxWaitTimeMs,
    };
}

function toNativeArrowOptions(
    o: CreateArrowStreamOptions,
): native.ArrowStreamConfigurationOptions {
    return {
        recovery: o.recovery,
        recoveryTimeoutMs: o.recoveryTimeoutMs,
        recoveryBackoffMs: o.recoveryBackoffMs,
        recoveryRetries: o.recoveryRetries,
        serverLackOfAckTimeoutMs: o.serverLackOfAckTimeoutMs,
        flushTimeoutMs: o.flushTimeoutMs,
        maxInflightBatches: o.maxInflightBatches,
        connectionTimeoutMs: o.connectionTimeoutMs,
        streamPausedMaxWaitTimeMs: o.streamPausedMaxWaitTimeMs,
        ipcCompression: compressionToNative(o.compression),
    };
}

// ---------------------------------------------------------------------------
// Public classes
// ---------------------------------------------------------------------------

/**
 * Entry point for opening ingestion streams against Zerobus.
 *
 * @example
 * ```typescript
 * const sdk = new ZerobusSdk({
 *     endpoint: 'https://workspace.zerobus.databricks.com',
 *     unityCatalogUrl: 'https://workspace.cloud.databricks.com',
 *     applicationName: 'my-service/1.0',
 * });
 *
 * const stream = await sdk.createStream({
 *     table: 'catalog.schema.table',
 *     auth: { type: 'oauth', clientId, clientSecret },
 *     format: { type: 'json' },
 * });
 * ```
 */
export class ZerobusSdk {
    /** @internal */ readonly native: native.ZerobusSdk;

    constructor(options: SdkOptions) {
        if (!options?.endpoint) {
            throw new Error('ZerobusSdk: options.endpoint is required');
        }
        this.native = new native.ZerobusSdk({
            endpoint: options.endpoint,
            unityCatalogUrl: options.unityCatalogUrl,
            useTls: options.tls === 'none' ? false : true,
            applicationName: options.applicationName,
            sdkIdentifier: options.sdkIdentifier,
        });
    }

    async createStream(options: CreateStreamOptions): Promise<ZerobusStream> {
        const native_auth = authToNative(options.auth, options.table);
        const descriptor =
            options.format.type === 'proto' ? options.format.descriptor : undefined;
        const tableProps: native.TableProperties = {
            tableName: options.table,
            descriptorProto: descriptor,
        };
        const stream = await this.native.createStream(
            tableProps,
            native_auth.clientId,
            native_auth.clientSecret,
            toNativeStreamOptions(options),
            native_auth.headersProvider,
        );
        return new ZerobusStream(stream);
    }

    async createArrowStream(
        options: CreateArrowStreamOptions,
    ): Promise<ZerobusArrowStream> {
        const native_auth = authToNative(options.auth, options.table);
        const NativeSdk = this.native as native.ZerobusSdk & {
            createArrowStream(
                tableProperties: native.ArrowTableProperties,
                clientId: string,
                clientSecret: string,
                options?: native.ArrowStreamConfigurationOptions,
                headersProvider?: native.JsHeadersProvider,
            ): Promise<native.ZerobusArrowStream>;
        };
        const tableProps: native.ArrowTableProperties = {
            tableName: options.table,
            schemaFields: options.schema.map((f) => ({
                name: f.name,
                dataType: f.dataType as unknown as number,
                nullable: f.nullable,
            })),
        };
        const stream = await NativeSdk.createArrowStream(
            tableProps,
            native_auth.clientId,
            native_auth.clientSecret,
            toNativeArrowOptions(options),
            native_auth.headersProvider,
        );
        return new ZerobusArrowStream(stream);
    }

    async recreateStream(stream: ZerobusStream): Promise<ZerobusStream> {
        const fresh = await this.native.recreateStream(stream.native);
        return new ZerobusStream(fresh);
    }

    async recreateArrowStream(stream: ZerobusArrowStream): Promise<ZerobusArrowStream> {
        const NativeSdk = this.native as native.ZerobusSdk & {
            recreateArrowStream(s: native.ZerobusArrowStream): Promise<native.ZerobusArrowStream>;
        };
        const fresh = await NativeSdk.recreateArrowStream(stream.native);
        return new ZerobusArrowStream(fresh);
    }
}

export class ZerobusStream {
    /** @internal */ readonly native: native.ZerobusStream;

    /** @internal */
    constructor(n: native.ZerobusStream) {
        this.native = n;
    }

    /**
     * Queue a single record. Resolves to the offset ID once the record is in
     * the SDK's landing zone — does NOT wait for server ack. Use
     * {@link waitForOffset} to wait.
     *
     * The record argument is interpreted by JS type:
     * - `Buffer` → raw protobuf bytes
     * - `string` → raw JSON
     * - object with `.encode()` → protobufjs message (auto-encoded)
     * - plain object → JSON.stringify'd
     */
    ingestRecord(record: unknown): Promise<bigint> {
        return this.native.ingestRecordOffset(record);
    }

    /** Queue many records atomically. Resolves to `null` for an empty array. */
    ingestRecords(records: unknown[]): Promise<bigint | null> {
        return this.native.ingestRecordsOffset(records);
    }

    waitForOffset(offset: bigint): Promise<void> {
        return this.native.waitForOffset(offset);
    }

    flush(): Promise<void> {
        return this.native.flush();
    }

    close(): Promise<void> {
        return this.native.close();
    }

    /** Unacked records as raw payload buffers. */
    getUnackedRecords(): Promise<Buffer[]> {
        return this.native.getUnackedRecords();
    }

    /** Unacked records grouped by batch. */
    getUnackedBatches(): Promise<Buffer[][]> {
        return this.native.getUnackedBatches();
    }
}

/**
 * Arrow Flight ingestion stream (Beta).
 *
 * The API is stabilising but may still change before reaching GA.
 */
export class ZerobusArrowStream {
    /** @internal */ readonly native: native.ZerobusArrowStream;

    /** @internal */
    constructor(n: native.ZerobusArrowStream) {
        this.native = n;
    }

    /**
     * Ingest one RecordBatch encoded as an Arrow IPC stream
     * (`tableToIPC(table, 'stream')` from `apache-arrow`).
     *
     * When the stream was opened without compression, the IPC bytes are
     * forwarded directly to Flight (zero-copy). When compression was
     * configured, the SDK parses the batch and re-encodes with the codec.
     */
    ingestBatch(ipcBuffer: Buffer): Promise<bigint> {
        return this.native.ingestBatch(ipcBuffer);
    }

    waitForOffset(offset: bigint): Promise<void> {
        return this.native.waitForOffset(offset);
    }

    flush(): Promise<void> {
        return this.native.flush();
    }

    close(): Promise<void> {
        return this.native.close();
    }

    get isClosed(): boolean {
        return this.native.isClosed;
    }

    get tableName(): string {
        return this.native.tableName;
    }

    getUnackedBatches(): Promise<Buffer[]> {
        return this.native.getUnackedBatches();
    }
}
