<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Databricks.Zerobus.Tools.GenerateProto</RootNamespace>
    <AssemblyName>generate-proto</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Databricks.Zerobus\Databricks.Zerobus.csproj" />
    <PackageReference Include="Google.Protobuf" Version="3.28.2" />
  </ItemGroup>

</Project>
