[package]
name = "example_arrow"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
databricks-zerobus-ingest-sdk = { path = "../../sdk", features = ["arrow-flight"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
chrono.workspace = true
arrow-array.workspace = true
arrow-ipc.workspace = true
