name: Auto PR to main

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          title: "PR: ${{ github.ref_name }} → main"
          body: "This PR was automatically created when pushing `${{ github.ref_name }}`."
          draft: true
