[package]
name = "tools"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
databricks-zerobus-ingest-sdk = { path = "../../sdk" }
prost-types.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tonic-prost-build.workspace = true
urlencoding.workspace = true

[build-dependencies]
protoc-bin-vendored.workspace = true

[dev-dependencies]
tempfile.workspace = true
