// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.0
// source: zerobus_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Zerobus_EphemeralStream_FullMethodName = "/databricks.zerobus.Zerobus/EphemeralStream"
)

// ZerobusClient is the client API for Zerobus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Zerobus service provides streaming capabilities for ingesting data records
// into Databricks tables with high throughput and low latency.
type ZerobusClient interface {
	// EphemeralStream creates a streaming session for ingesting records.
	//
	// This is a bidirectional streaming RPC that allows clients to:
	// - Create new ephemeral ingestion streams by sending a CreateIngestStreamRequest.
	// - Ingest records by sending an IngestRecordRequest.
	// - Receive durability confirmations via IngestRecordResponse.
	EphemeralStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EphemeralStreamRequest, EphemeralStreamResponse], error)
}

type zerobusClient struct {
	cc grpc.ClientConnInterface
}

func NewZerobusClient(cc grpc.ClientConnInterface) ZerobusClient {
	return &zerobusClient{cc}
}

func (c *zerobusClient) EphemeralStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EphemeralStreamRequest, EphemeralStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Zerobus_ServiceDesc.Streams[0], Zerobus_EphemeralStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EphemeralStreamRequest, EphemeralStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Zerobus_EphemeralStreamClient = grpc.BidiStreamingClient[EphemeralStreamRequest, EphemeralStreamResponse]

// ZerobusServer is the server API for Zerobus service.
// All implementations must embed UnimplementedZerobusServer
// for forward compatibility.
//
// The Zerobus service provides streaming capabilities for ingesting data records
// into Databricks tables with high throughput and low latency.
type ZerobusServer interface {
	// EphemeralStream creates a streaming session for ingesting records.
	//
	// This is a bidirectional streaming RPC that allows clients to:
	// - Create new ephemeral ingestion streams by sending a CreateIngestStreamRequest.
	// - Ingest records by sending an IngestRecordRequest.
	// - Receive durability confirmations via IngestRecordResponse.
	EphemeralStream(grpc.BidiStreamingServer[EphemeralStreamRequest, EphemeralStreamResponse]) error
	mustEmbedUnimplementedZerobusServer()
}

// UnimplementedZerobusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZerobusServer struct{}

func (UnimplementedZerobusServer) EphemeralStream(grpc.BidiStreamingServer[EphemeralStreamRequest, EphemeralStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method EphemeralStream not implemented")
}
func (UnimplementedZerobusServer) mustEmbedUnimplementedZerobusServer() {}
func (UnimplementedZerobusServer) testEmbeddedByValue()                 {}

// UnsafeZerobusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZerobusServer will
// result in compilation errors.
type UnsafeZerobusServer interface {
	mustEmbedUnimplementedZerobusServer()
}

func RegisterZerobusServer(s grpc.ServiceRegistrar, srv ZerobusServer) {
	// If the following call panics, it indicates UnimplementedZerobusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Zerobus_ServiceDesc, srv)
}

func _Zerobus_EphemeralStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZerobusServer).EphemeralStream(&grpc.GenericServerStream[EphemeralStreamRequest, EphemeralStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Zerobus_EphemeralStreamServer = grpc.BidiStreamingServer[EphemeralStreamRequest, EphemeralStreamResponse]

// Zerobus_ServiceDesc is the grpc.ServiceDesc for Zerobus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zerobus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "databricks.zerobus.Zerobus",
	HandlerType: (*ZerobusServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EphemeralStream",
			Handler:       _Zerobus_EphemeralStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "zerobus_service.proto",
}
