"use strict";

/**
 * Utility functions for working with Protocol Buffer descriptors.
 *
 * These utilities help extract message descriptors from FileDescriptorSets
 * generated by protoc, providing flexibility in choosing which message to use.
 */

const fs = require("fs");
const descriptor = require("protobufjs/ext/descriptor");

/**
 * Loads a specific message's DescriptorProto from a FileDescriptorSet.
 *
 * @param {object} options
 * @param {string} options.descriptorPath Path to the descriptor file generated by protoc.
 * @param {string} options.protoFileName Name of the proto file within the FileDescriptorSet.
 * @param {string} options.messageName Name of the message type to extract.
 * @returns {string} Base64-encoded DescriptorProto string for the specified message.
 */
function loadDescriptorProto(options) {
    const { descriptorPath, protoFileName, messageName } = options;

    const descriptorBytes = fs.readFileSync(descriptorPath);
    const fileDescriptorSet = descriptor.FileDescriptorSet.decode(descriptorBytes);
    const fileDescriptor = fileDescriptorSet.file.find((file) =>
        file.name === protoFileName ||
        file.name.endsWith("/" + protoFileName)
    );

    if (!fileDescriptor) {
        throw new Error(
            `Proto file '${protoFileName}' not found in descriptor. Available files: ${
                fileDescriptorSet.file.map((file) => file.name).join(", ")
            }`
        );
    }

    const messageType = fileDescriptor.messageType?.find((message) => message.name === messageName);

    if (!messageType) {
        const availableMessages = fileDescriptor.messageType?.map((message) => message.name).join(", ") || "none";
        throw new Error(
            `Message '${messageName}' not found in ${protoFileName}. Available messages: ${availableMessages}`
        );
    }

    const descriptorProtoBytes = descriptor.DescriptorProto.encode(messageType).finish();
    return Buffer.from(descriptorProtoBytes).toString("base64");
}

module.exports = {
    loadDescriptorProto,
};
