/**
 * Options for loading a descriptor from a FileDescriptorSet.
 */
export interface LoadDescriptorOptions {
    /**
     * Path to the descriptor file generated by protoc.
     * Example: 'schemas/my_schema_descriptor.pb'
     */
    descriptorPath: string;

    /**
     * Name of the proto file within the FileDescriptorSet.
     * This should match the filename in your .proto file.
     * Example: 'schemas/air_quality.proto' or 'air_quality.proto'
     */
    protoFileName: string;

    /**
     * Name of the message type to extract.
     * Example: 'AirQuality'
     */
    messageName: string;
}

/**
 * Loads a specific message's DescriptorProto from a FileDescriptorSet.
 *
 * @param options - Configuration specifying which message to extract
 * @returns Base64-encoded DescriptorProto string for the specified message
 * @throws Error if the descriptor file, proto file, or message cannot be found
 */
export function loadDescriptorProto(options: LoadDescriptorOptions): string;
