[package]
name = "rust-examples-proto"
version = "0.1.0"
edition = "2021"
publish = false

[[example]]
name = "proto_compiled_batch"
path = "compiled/batch.rs"

[[example]]
name = "proto_compiled_single"
path = "compiled/single.rs"

[[example]]
name = "proto_compiled_multiplexed"
path = "compiled/multiplexed.rs"

[[example]]
name = "proto_dynamic_batch"
path = "dynamic/batch.rs"

[[example]]
name = "proto_dynamic_single"
path = "dynamic/single.rs"

[dependencies]
databricks-zerobus-ingest-sdk = { path = "../../sdk" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
chrono.workspace = true
prost.workspace = true
prost-reflect.workspace = true
