[package]
name = "rust-examples-proto"
version = "0.1.0"
edition = "2021"
publish = false

[[example]]
name = "proto_batch"
path = "batch.rs"

[[example]]
name = "proto_single"
path = "single.rs"

[[example]]
name = "proto_dynamic"
path = "dynamic.rs"

[dependencies]
databricks-zerobus-ingest-sdk = { path = "../../sdk" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
chrono.workspace = true
prost.workspace = true
prost-reflect.workspace = true
serde_json.workspace = true
