// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: zerobus_service.proto

package zerobuspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordType int32

const (
	RecordType_RECORD_TYPE_UNSPECIFIED RecordType = 0
	RecordType_PROTO                   RecordType = 1
	RecordType_JSON                    RecordType = 2
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "RECORD_TYPE_UNSPECIFIED",
		1: "PROTO",
		2: "JSON",
	}
	RecordType_value = map[string]int32{
		"RECORD_TYPE_UNSPECIFIED": 0,
		"PROTO":                   1,
		"JSON":                    2,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_zerobus_service_proto_enumTypes[0].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_zerobus_service_proto_enumTypes[0]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RecordType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RecordType(num)
	return nil
}

// Deprecated: Use RecordType.Descriptor instead.
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return file_zerobus_service_proto_rawDescGZIP(), []int{0}
}

type JsonRecordBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []string               `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonRecordBatch) Reset() {
	*x = JsonRecordBatch{}
	mi := &file_zerobus_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonRecordBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonRecordBatch) ProtoMessage() {}

func (x *JsonRecordBatch) ProtoReflect() protoreflect.Message {
	mi := &file_zerobus_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonRecordBatch.ProtoReflect.Descriptor instead.
func (*JsonRecordBatch) Descriptor() ([]byte, []int) {
	return file_zerobus_service_proto_rawDescGZIP(), []int{0}
}

func (x *JsonRecordBatch) GetRecords() []string {
	if x != nil {
		return x.Records
	}
	return nil
}

type ProtoEncodedRecordBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       [][]byte               `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoEncodedRecordBatch) Reset() {
	*x = ProtoEncodedRecordBatch{}
	mi := &file_zerobus_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoEncodedRecordBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoEncodedRecordBatch) ProtoMessage() {}

func (x *ProtoEncodedRecordBatch) ProtoReflect() protoreflect.Message {
	mi := &file_zerobus_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoEncodedRecordBatch.ProtoReflect.Descriptor instead.
func (*ProtoEncodedRecordBatch) Descriptor() ([]byte, []int) {
	return file_zerobus_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoEncodedRecordBatch) GetRecords() [][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

type CreateIngestStreamRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TableName       *string                `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	DescriptorProto []byte                 `protobuf:"bytes,3,opt,name=descriptor_proto,json=descriptorProto" json:"descriptor_proto,omitempty"`
	RecordType      *RecordType            `protobuf:"varint,4,opt,name=record_type,json=recordType,enum=databricks.zerobus.RecordType" json:"record_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateIngestStreamRequest) Reset() {
	*x = CreateIngestStreamRequest{}
	mi := &file_zerobus_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIngestStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngestStreamRequest) ProtoMessage() {}

func (x *CreateIngestStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerobus_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngestStreamRequest.ProtoReflect.Descriptor instead.
func (*CreateIngestStreamRequest) Descriptor() ([]byte, []int) {
	return file_zerobus_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIngestStreamRequest) GetTableName() string {
	if x != nil && x.TableName != nil {
		return *x.TableName
	}
	return ""
}

func (x *CreateIngestStreamRequest) GetDescriptorProto() []byte {
	if x != nil {
		return x.DescriptorProto
	}
	return nil
}

func (x *CreateIngestStreamRequest) GetRecordType() RecordType {
	if x != nil && x.RecordType != nil {
		return *x.RecordType
	}
	return RecordType_RECORD_TYPE_UNSPECIFIED
}

type CreateIngestStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      *string                `protobuf:"bytes,1,opt,name=stream_id,json=streamId" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIngestStreamResponse) Reset() {
	*x = CreateIngestStreamResponse{}
	mi := &file_zerobus_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIngestStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngestStreamResponse) ProtoMessage() {}

func (x *CreateIngestStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerobus_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngestStreamResponse.ProtoReflect.Descriptor instead.
func (*CreateIngestStreamResponse) Descriptor() ([]byte, []int) {
	return file_zerobus_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateIngestStreamResponse) GetStreamId() string {
	if x != nil && x.StreamId != nil {
		return *x.StreamId
	}
	return ""
}

type IngestRecordRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	OffsetId *int64                 `protobuf:"varint,1,opt,name=offset_id,json=offsetId" json:"offset_id,omitempty"`
	// Types that are valid to be assigned to Record:
	//
	//	*IngestRecordRequest_ProtoEncodedRecord
	//	*IngestRecordRequest_JsonRecord
	Record        isIngestRecordRequest_Record `protobuf_oneof:"record"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRecordRequest) Reset() {
	*x = IngestRecordRequest{}
	mi := &file_zerobus_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRecordRequest) ProtoMessage() {}

func (x *IngestRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerobus_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRecordRequest.ProtoReflect.Descriptor instead.
func (*IngestRecordRequest) Descriptor() ([]byte, []int) {
	return file_zerobus_service_proto_rawDescGZIP(), []int{4}
}

func (x *IngestRecordRequest) GetOffsetId() int64 {
	if x != nil && x.OffsetId != nil {
		return *x.OffsetId
	}
	return 0
}

func (x *IngestRecordRequest) GetRecord() isIngestRecordRequest_Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *IngestRecordRequest) GetProtoEncodedRecord() []byte {
	if x != nil {
		if x, ok := x.Record.(*IngestRecordRequest_ProtoEncodedRecord); ok {
			return x.ProtoEncodedRecord
		}
	}
	return nil
}

func (x *IngestRecordRequest) GetJsonRecord() string {
	if x != nil {
		if x, ok := x.Record.(*IngestRecordRequest_JsonRecord); ok {
			return x.JsonRecord
		}
	}
	return ""
}

type isIngestRecordRequest_Record interface {
	isIngestRecordRequest_Record()
}

type IngestRecordRequest_ProtoEncodedRecord struct {
	ProtoEncodedRecord []byte `protobuf:"bytes,2,opt,name=proto_encoded_record,json=protoEncodedRecord,oneof"`
}

type IngestRecordRequest_JsonRecord struct {
	JsonRecord string `protobuf:"bytes,3,opt,name=json_record,json=jsonRecord,oneof"`
}

func (*IngestRecordRequest_ProtoEncodedRecord) isIngestRecordRequest_Record() {}

func (*IngestRecordRequest_JsonRecord) isIngestRecordRequest_Record() {}

type IngestRecordBatchRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	OffsetId *int64                 `protobuf:"varint,1,opt,name=offset_id,json=offsetId" json:"offset_id,omitempty"`
	// Types that are valid to be assigned to Batch:
	//
	//	*IngestRecordBatchRequest_ProtoEncodedBatch
	//	*IngestRecordBatchRequest_JsonBatch
	Batch         isIngestRecordBatchRequest_Batch `protobuf_oneof:"batch"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRecordBatchRequest) Reset() {
	*x = IngestRecordBatchRequest{}
	mi := &file_zerobus_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRecordBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRecordBatchRequest) ProtoMessage() {}

func (x *IngestRecordBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerobus_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRecordBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestRecordBatchRequest) Descriptor() ([]byte, []int) {
	return file_zerobus_service_proto_rawDescGZIP(), []int{5}
}

func (x *IngestRecordBatchRequest) GetOffsetId() int64 {
	if x != nil && x.OffsetId != nil {
		return *x.OffsetId
	}
	return 0
}

func (x *IngestRecordBatchRequest) GetBatch() isIngestRecordBatchRequest_Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *IngestRecordBatchRequest) GetProtoEncodedBatch() *ProtoEncodedRecordBatch {
	if x != nil {
		if x, ok := x.Batch.(*IngestRecordBatchRequest_ProtoEncodedBatch); ok {
			return x.ProtoEncodedBatch
		}
	}
	return nil
}

func (x *IngestRecordBatchRequest) GetJsonBatch() *JsonRecordBatch {
	if x != nil {
		if x, ok := x.Batch.(*IngestRecordBatchRequest_JsonBatch); ok {
			return x.JsonBatch
		}
	}
	return nil
}

type isIngestRecordBatchRequest_Batch interface {
	isIngestRecordBatchRequest_Batch()
}

type IngestRecordBatchRequest_ProtoEncodedBatch struct {
	ProtoEncodedBatch *ProtoEncodedRecordBatch `protobuf:"bytes,2,opt,name=proto_encoded_batch,json=protoEncodedBatch,oneof"`
}

type IngestRecordBatchRequest_JsonBatch struct {
	JsonBatch *JsonRecordBatch `protobuf:"bytes,3,opt,name=json_batch,json=jsonBatch,oneof"`
}

func (*IngestRecordBatchRequest_ProtoEncodedBatch) isIngestRecordBatchRequest_Batch() {}

func (*IngestRecordBatchRequest_JsonBatch) isIngestRecordBatchRequest_Batch() {}

type EphemeralStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EphemeralStreamRequest_CreateStream
	//	*EphemeralStreamRequest_IngestRecord
	//	*EphemeralStreamRequest_IngestRecordBatch
	Payload       isEphemeralStreamRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EphemeralStreamRequest) Reset() {
	*x = EphemeralStreamRequest{}
	mi := &file_zerobus_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EphemeralStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EphemeralStreamRequest) ProtoMessage() {}

func (x *EphemeralStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zerobus_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EphemeralStreamRequest.ProtoReflect.Descriptor instead.
func (*EphemeralStreamRequest) Descriptor() ([]byte, []int) {
	return file_zerobus_service_proto_rawDescGZIP(), []int{6}
}

func (x *EphemeralStreamRequest) GetPayload() isEphemeralStreamRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EphemeralStreamRequest) GetCreateStream() *CreateIngestStreamRequest {
	if x != nil {
		if x, ok := x.Payload.(*EphemeralStreamRequest_CreateStream); ok {
			return x.CreateStream
		}
	}
	return nil
}

func (x *EphemeralStreamRequest) GetIngestRecord() *IngestRecordRequest {
	if x != nil {
		if x, ok := x.Payload.(*EphemeralStreamRequest_IngestRecord); ok {
			return x.IngestRecord
		}
	}
	return nil
}

func (x *EphemeralStreamRequest) GetIngestRecordBatch() *IngestRecordBatchRequest {
	if x != nil {
		if x, ok := x.Payload.(*EphemeralStreamRequest_IngestRecordBatch); ok {
			return x.IngestRecordBatch
		}
	}
	return nil
}

type isEphemeralStreamRequest_Payload interface {
	isEphemeralStreamRequest_Payload()
}

type EphemeralStreamRequest_CreateStream struct {
	CreateStream *CreateIngestStreamRequest `protobuf:"bytes,1,opt,name=create_stream,json=createStream,oneof"`
}

type EphemeralStreamRequest_IngestRecord struct {
	IngestRecord *IngestRecordRequest `protobuf:"bytes,2,opt,name=ingest_record,json=ingestRecord,oneof"`
}

type EphemeralStreamRequest_IngestRecordBatch struct {
	IngestRecordBatch *IngestRecordBatchRequest `protobuf:"bytes,3,opt,name=ingest_record_batch,json=ingestRecordBatch,oneof"`
}

func (*EphemeralStreamRequest_CreateStream) isEphemeralStreamRequest_Payload() {}

func (*EphemeralStreamRequest_IngestRecord) isEphemeralStreamRequest_Payload() {}

func (*EphemeralStreamRequest_IngestRecordBatch) isEphemeralStreamRequest_Payload() {}

type IngestRecordResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DurabilityAckUpToOffset *int64                 `protobuf:"varint,1,opt,name=durability_ack_up_to_offset,json=durabilityAckUpToOffset" json:"durability_ack_up_to_offset,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *IngestRecordResponse) Reset() {
	*x = IngestRecordResponse{}
	mi := &file_zerobus_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRecordResponse) ProtoMessage() {}

func (x *IngestRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerobus_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRecordResponse.ProtoReflect.Descriptor instead.
func (*IngestRecordResponse) Descriptor() ([]byte, []int) {
	return file_zerobus_service_proto_rawDescGZIP(), []int{7}
}

func (x *IngestRecordResponse) GetDurabilityAckUpToOffset() int64 {
	if x != nil && x.DurabilityAckUpToOffset != nil {
		return *x.DurabilityAckUpToOffset
	}
	return 0
}

type CloseStreamSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      *durationpb.Duration   `protobuf:"bytes,1,opt,name=duration" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStreamSignal) Reset() {
	*x = CloseStreamSignal{}
	mi := &file_zerobus_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStreamSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStreamSignal) ProtoMessage() {}

func (x *CloseStreamSignal) ProtoReflect() protoreflect.Message {
	mi := &file_zerobus_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStreamSignal.ProtoReflect.Descriptor instead.
func (*CloseStreamSignal) Descriptor() ([]byte, []int) {
	return file_zerobus_service_proto_rawDescGZIP(), []int{8}
}

func (x *CloseStreamSignal) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type EphemeralStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EphemeralStreamResponse_CreateStreamResponse
	//	*EphemeralStreamResponse_IngestRecordResponse
	//	*EphemeralStreamResponse_CloseStreamSignal
	Payload       isEphemeralStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EphemeralStreamResponse) Reset() {
	*x = EphemeralStreamResponse{}
	mi := &file_zerobus_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EphemeralStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EphemeralStreamResponse) ProtoMessage() {}

func (x *EphemeralStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zerobus_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EphemeralStreamResponse.ProtoReflect.Descriptor instead.
func (*EphemeralStreamResponse) Descriptor() ([]byte, []int) {
	return file_zerobus_service_proto_rawDescGZIP(), []int{9}
}

func (x *EphemeralStreamResponse) GetPayload() isEphemeralStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EphemeralStreamResponse) GetCreateStreamResponse() *CreateIngestStreamResponse {
	if x != nil {
		if x, ok := x.Payload.(*EphemeralStreamResponse_CreateStreamResponse); ok {
			return x.CreateStreamResponse
		}
	}
	return nil
}

func (x *EphemeralStreamResponse) GetIngestRecordResponse() *IngestRecordResponse {
	if x != nil {
		if x, ok := x.Payload.(*EphemeralStreamResponse_IngestRecordResponse); ok {
			return x.IngestRecordResponse
		}
	}
	return nil
}

func (x *EphemeralStreamResponse) GetCloseStreamSignal() *CloseStreamSignal {
	if x != nil {
		if x, ok := x.Payload.(*EphemeralStreamResponse_CloseStreamSignal); ok {
			return x.CloseStreamSignal
		}
	}
	return nil
}

type isEphemeralStreamResponse_Payload interface {
	isEphemeralStreamResponse_Payload()
}

type EphemeralStreamResponse_CreateStreamResponse struct {
	CreateStreamResponse *CreateIngestStreamResponse `protobuf:"bytes,1,opt,name=create_stream_response,json=createStreamResponse,oneof"`
}

type EphemeralStreamResponse_IngestRecordResponse struct {
	IngestRecordResponse *IngestRecordResponse `protobuf:"bytes,2,opt,name=ingest_record_response,json=ingestRecordResponse,oneof"`
}

type EphemeralStreamResponse_CloseStreamSignal struct {
	CloseStreamSignal *CloseStreamSignal `protobuf:"bytes,3,opt,name=close_stream_signal,json=closeStreamSignal,oneof"`
}

func (*EphemeralStreamResponse_CreateStreamResponse) isEphemeralStreamResponse_Payload() {}

func (*EphemeralStreamResponse_IngestRecordResponse) isEphemeralStreamResponse_Payload() {}

func (*EphemeralStreamResponse_CloseStreamSignal) isEphemeralStreamResponse_Payload() {}

var File_zerobus_service_proto protoreflect.FileDescriptor

const file_zerobus_service_proto_rawDesc = "" +
	"\n" +
	"\x15zerobus_service.proto\x12\x12databricks.zerobus\x1a\x1egoogle/protobuf/duration.proto\"+\n" +
	"\x0fJsonRecordBatch\x12\x18\n" +
	"\arecords\x18\x01 \x03(\tR\arecords\"3\n" +
	"\x17ProtoEncodedRecordBatch\x12\x18\n" +
	"\arecords\x18\x01 \x03(\fR\arecords\"\xb7\x01\n" +
	"\x19CreateIngestStreamRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12)\n" +
	"\x10descriptor_proto\x18\x03 \x01(\fR\x0fdescriptorProto\x12?\n" +
	"\vrecord_type\x18\x04 \x01(\x0e2\x1e.databricks.zerobus.RecordTypeR\n" +
	"recordTypeJ\x04\b\x02\x10\x03R\tstream_id\"O\n" +
	"\x1aCreateIngestStreamResponse\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamIdJ\x04\b\x02\x10\x03R\x0elast_offset_id\"\x93\x01\n" +
	"\x13IngestRecordRequest\x12\x1b\n" +
	"\toffset_id\x18\x01 \x01(\x03R\boffsetId\x122\n" +
	"\x14proto_encoded_record\x18\x02 \x01(\fH\x00R\x12protoEncodedRecord\x12!\n" +
	"\vjson_record\x18\x03 \x01(\tH\x00R\n" +
	"jsonRecordB\b\n" +
	"\x06record\"\xe5\x01\n" +
	"\x18IngestRecordBatchRequest\x12\x1b\n" +
	"\toffset_id\x18\x01 \x01(\x03R\boffsetId\x12]\n" +
	"\x13proto_encoded_batch\x18\x02 \x01(\v2+.databricks.zerobus.ProtoEncodedRecordBatchH\x00R\x11protoEncodedBatch\x12D\n" +
	"\n" +
	"json_batch\x18\x03 \x01(\v2#.databricks.zerobus.JsonRecordBatchH\x00R\tjsonBatchB\a\n" +
	"\x05batch\"\xa9\x02\n" +
	"\x16EphemeralStreamRequest\x12T\n" +
	"\rcreate_stream\x18\x01 \x01(\v2-.databricks.zerobus.CreateIngestStreamRequestH\x00R\fcreateStream\x12N\n" +
	"\ringest_record\x18\x02 \x01(\v2'.databricks.zerobus.IngestRecordRequestH\x00R\fingestRecord\x12^\n" +
	"\x13ingest_record_batch\x18\x03 \x01(\v2,.databricks.zerobus.IngestRecordBatchRequestH\x00R\x11ingestRecordBatchB\t\n" +
	"\apayload\"T\n" +
	"\x14IngestRecordResponse\x12<\n" +
	"\x1bdurability_ack_up_to_offset\x18\x01 \x01(\x03R\x17durabilityAckUpToOffset\"J\n" +
	"\x11CloseStreamSignal\x125\n" +
	"\bduration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bduration\"\xc7\x02\n" +
	"\x17EphemeralStreamResponse\x12f\n" +
	"\x16create_stream_response\x18\x01 \x01(\v2..databricks.zerobus.CreateIngestStreamResponseH\x00R\x14createStreamResponse\x12`\n" +
	"\x16ingest_record_response\x18\x02 \x01(\v2(.databricks.zerobus.IngestRecordResponseH\x00R\x14ingestRecordResponse\x12W\n" +
	"\x13close_stream_signal\x18\x03 \x01(\v2%.databricks.zerobus.CloseStreamSignalH\x00R\x11closeStreamSignalB\t\n" +
	"\apayload*>\n" +
	"\n" +
	"RecordType\x12\x1b\n" +
	"\x17RECORD_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05PROTO\x10\x01\x12\b\n" +
	"\x04JSON\x10\x022y\n" +
	"\aZerobus\x12n\n" +
	"\x0fEphemeralStream\x12*.databricks.zerobus.EphemeralStreamRequest\x1a+.databricks.zerobus.EphemeralStreamResponse(\x010\x01B9Z7github.com/databricks/zerobus-sdk/go/internal/zerobuspb"

var (
	file_zerobus_service_proto_rawDescOnce sync.Once
	file_zerobus_service_proto_rawDescData []byte
)

func file_zerobus_service_proto_rawDescGZIP() []byte {
	file_zerobus_service_proto_rawDescOnce.Do(func() {
		file_zerobus_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zerobus_service_proto_rawDesc), len(file_zerobus_service_proto_rawDesc)))
	})
	return file_zerobus_service_proto_rawDescData
}

var file_zerobus_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zerobus_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_zerobus_service_proto_goTypes = []any{
	(RecordType)(0),                    // 0: databricks.zerobus.RecordType
	(*JsonRecordBatch)(nil),            // 1: databricks.zerobus.JsonRecordBatch
	(*ProtoEncodedRecordBatch)(nil),    // 2: databricks.zerobus.ProtoEncodedRecordBatch
	(*CreateIngestStreamRequest)(nil),  // 3: databricks.zerobus.CreateIngestStreamRequest
	(*CreateIngestStreamResponse)(nil), // 4: databricks.zerobus.CreateIngestStreamResponse
	(*IngestRecordRequest)(nil),        // 5: databricks.zerobus.IngestRecordRequest
	(*IngestRecordBatchRequest)(nil),   // 6: databricks.zerobus.IngestRecordBatchRequest
	(*EphemeralStreamRequest)(nil),     // 7: databricks.zerobus.EphemeralStreamRequest
	(*IngestRecordResponse)(nil),       // 8: databricks.zerobus.IngestRecordResponse
	(*CloseStreamSignal)(nil),          // 9: databricks.zerobus.CloseStreamSignal
	(*EphemeralStreamResponse)(nil),    // 10: databricks.zerobus.EphemeralStreamResponse
	(*durationpb.Duration)(nil),        // 11: google.protobuf.Duration
}
var file_zerobus_service_proto_depIdxs = []int32{
	0,  // 0: databricks.zerobus.CreateIngestStreamRequest.record_type:type_name -> databricks.zerobus.RecordType
	2,  // 1: databricks.zerobus.IngestRecordBatchRequest.proto_encoded_batch:type_name -> databricks.zerobus.ProtoEncodedRecordBatch
	1,  // 2: databricks.zerobus.IngestRecordBatchRequest.json_batch:type_name -> databricks.zerobus.JsonRecordBatch
	3,  // 3: databricks.zerobus.EphemeralStreamRequest.create_stream:type_name -> databricks.zerobus.CreateIngestStreamRequest
	5,  // 4: databricks.zerobus.EphemeralStreamRequest.ingest_record:type_name -> databricks.zerobus.IngestRecordRequest
	6,  // 5: databricks.zerobus.EphemeralStreamRequest.ingest_record_batch:type_name -> databricks.zerobus.IngestRecordBatchRequest
	11, // 6: databricks.zerobus.CloseStreamSignal.duration:type_name -> google.protobuf.Duration
	4,  // 7: databricks.zerobus.EphemeralStreamResponse.create_stream_response:type_name -> databricks.zerobus.CreateIngestStreamResponse
	8,  // 8: databricks.zerobus.EphemeralStreamResponse.ingest_record_response:type_name -> databricks.zerobus.IngestRecordResponse
	9,  // 9: databricks.zerobus.EphemeralStreamResponse.close_stream_signal:type_name -> databricks.zerobus.CloseStreamSignal
	7,  // 10: databricks.zerobus.Zerobus.EphemeralStream:input_type -> databricks.zerobus.EphemeralStreamRequest
	10, // 11: databricks.zerobus.Zerobus.EphemeralStream:output_type -> databricks.zerobus.EphemeralStreamResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_zerobus_service_proto_init() }
func file_zerobus_service_proto_init() {
	if File_zerobus_service_proto != nil {
		return
	}
	file_zerobus_service_proto_msgTypes[4].OneofWrappers = []any{
		(*IngestRecordRequest_ProtoEncodedRecord)(nil),
		(*IngestRecordRequest_JsonRecord)(nil),
	}
	file_zerobus_service_proto_msgTypes[5].OneofWrappers = []any{
		(*IngestRecordBatchRequest_ProtoEncodedBatch)(nil),
		(*IngestRecordBatchRequest_JsonBatch)(nil),
	}
	file_zerobus_service_proto_msgTypes[6].OneofWrappers = []any{
		(*EphemeralStreamRequest_CreateStream)(nil),
		(*EphemeralStreamRequest_IngestRecord)(nil),
		(*EphemeralStreamRequest_IngestRecordBatch)(nil),
	}
	file_zerobus_service_proto_msgTypes[9].OneofWrappers = []any{
		(*EphemeralStreamResponse_CreateStreamResponse)(nil),
		(*EphemeralStreamResponse_IngestRecordResponse)(nil),
		(*EphemeralStreamResponse_CloseStreamSignal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zerobus_service_proto_rawDesc), len(file_zerobus_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zerobus_service_proto_goTypes,
		DependencyIndexes: file_zerobus_service_proto_depIdxs,
		EnumInfos:         file_zerobus_service_proto_enumTypes,
		MessageInfos:      file_zerobus_service_proto_msgTypes,
	}.Build()
	File_zerobus_service_proto = out.File
	file_zerobus_service_proto_goTypes = nil
	file_zerobus_service_proto_depIdxs = nil
}
