name: CI

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  tests-ubuntu:
    uses: ./.github/workflows/test.yml
    with:
      os: linux-ubuntu-latest

  tests-windows:
    uses: ./.github/workflows/test.yml
    with:
      os: windows-server-latest

  fmt:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Format all files
        run: make fmt
      - name: Fail on differences
        run: git diff --exit-code

  lint:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Lint code
        run: make lint